[project]
name = 'stackhub-contracts'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.stackhub-nft-marketplace]
path = 'contracts/stackhub-nft-marketplace.clar'
clarity_version = 4
epoch = 'latest'

[contracts.stackhub-service-registry]
path = 'contracts/stackhub-service-registry.clar'
clarity_version = 4
epoch = 'latest'

[contracts.stackhub-staking-vault]
path = 'contracts/stackhub-staking-vault.clar'
clarity_version = 4
epoch = 'latest'

[contracts.stackhub-token-launchpad]
path = 'contracts/stackhub-token-launchpad.clar'
clarity_version = 4
epoch = 'latest'
[repl.analysis]
passes = [
    'call_checker',
    'check_checker',
]

[repl.analysis.lints]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
